version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: diego
      MYSQL_PASSWORD: diego
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysqlDb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8080:8080
